---
title: "workflow_outline"
format: html
---

# Overall aims
Develop a mechanistic model of human-human infectious disease transmission that will be largely disease agnostic but as specificity builds will resemble Ebola virus disease.

#

```{r}
set.seed(20260604)
individual_index <- 1:10


infection_status <- c(TRUE, rep(FALSE, 9))

```


Daily universal probabilities
```{r}
# probability_of_infection_per_contact if contact is infected
p_infection <- 0.1

# number of contacts each day for each individual
#n_contacts <- 2

# Create contact pairs prior to the timesteps
### NOTE THIS IS CURRENTLY IMPLEMENTED AS A GLOBAL PARAMETER BUT IT NEEDS TO BE INTERATED FOR EACH TIMESTEP

n_individuals <- length(individual_index) #contacts will be independent of infection status
n_contact_events <- 2*n_individuals

first_contact <- sample(x = individual_index, size = n_contact_events, replace = TRUE)
second_contact <- sample(x = individual_index, size = n_contact_events, replace = TRUE)

keep <- first_contact != second_contact 

# at the moment this allows for multiple contact events between the same pair in the same timestep
contact_pairs <- data.frame(first_contact = first_contact[keep], second_contact = second_contact[keep])

# for each individual list the indices of all people they contact in this timestep
# #for (i in individual_index) {
#   i = 2
#   contacts_1 <- contact_pairs$second_contact[contact_pairs$first_contact == i]
#   contacts_2 <- contact_pairs$first_contact[contact_pairs$second_contact == i]
#   contacts <- c(contacts_1, contacts_2)
#   contacts <- unique(contacts) # exclude multiple contact events between the same pair within the same timestep
# #}

```

```{r}
# For testing
index <- 3

infection_function <- function(
    index,
    prob_infection,
    contact_pairs,
    infection_status
  ){
  state <- infection_status[index]
  
  if(state) {
    return(TRUE)
  } else {
    # contacts <- sample(
    #   x = infection_status[-index],
    #   size = n_contacts,
    #   replace = FALSE
    # )
  contacts_1 <- contact_pairs$second_contact[contact_pairs$first_contact == index]
  contacts_2 <- contact_pairs$first_contact[contact_pairs$second_contact == index]
  contacts <- c(contacts_1, contacts_2)
  contacts <- unique(contacts) # exclude multiple contact events between the same pair within the same timestep
    
  contacted <- seq_along(infection_status) %in% contacts
  infectious_contacts <- infection_status & contacted   
    
    possible_infections <- prob_infection*infectious_contacts
    
    outcome <- rbinom(
      n = length(possible_infections),
      size = 1,
      prob = possible_infections
    )
    
    return(as.logical(max(outcome)))
    
  }
}

```

```{r}
# Time-steps

time_steps <- 10
infection_status_over_time <- matrix(nrow = time_steps, ncol = length(infection_status))
infection_status_over_time[1,] <- infection_status

for (t in 1:(time_steps-1)) {
  
  for (i in individual_index) {
    
    y <- infection_function(index = i, prob_infection = p_infection, contact_pairs = contact_pairs,  
                            infection_status = infection_status_over_time[t,])
    infection_status_over_time[t+1,i] <- y
  }
}

print(infection_status_over_time)


```


